- name: Remove the globally package azure
  npm:
    name: azure-functions-core-tools
    global: yes
    state: absent

- name: Uninstall function env packages
  package:
    name:
      - nodejs
      - npm
    state: absent
  become: True

- name: Recursively remove directory
  file:
    path: {{ mine_user_home }}/{{ function_name }}
    state: absent